FROM node:6.9.1

EXPOSE 4200 49152

ADD ./src /myapp

WORKDIR /myapp

ENTRYPOINT ["/usr/local/bin/ember"]

CMD ["server"]

RUN \
    npm install -g ember-cli@2.9.1 &&\
    npm install -g bower@1.8.0 &&\
    npm install -g phantomjs@2.1.7

RUN \
    git clone https://github.com/facebook/watchman.git &&\
    cd watchman &&\
    git checkout v3.5.0 &&\
    ./autogen.sh &&\
    ./configure &&\
    make &&\
    make install